# Generated by Django 5.1.2 on 2024-10-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
