# Generated by Django 5.1.2 on 2024-10-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_contact_email_id_alter_lead_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
