# Generated by Django 5.1.2 on 2024-10-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_contact_email_id_alter_lead_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_assignment',
            name='assigned_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
