# Generated by Django 5.1.2 on 2024-10-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_log_created_on_alter_note_note_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
    ]
