# Generated by Django 5.1.2 on 2024-10-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_opportunity_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.log'),
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
